name = "rc-goglbe"
main = "src/index.ts"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

# Static Assets (CSS, Fonts, Icons)
[assets]
directory = "./public"
binding = "ASSETS"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "rc-db"
database_id = "b8d47c58-581f-4839-8a42-c52290c41fdb"

# Environment Variables
[vars]
API_SECRET = "goglbe-edge-secret-2026"
